### PR TITLE
Add Java 12 memory profiling support

### PR DESCRIPTION
**Pull request by rraptorr**
_length was changed to _length_and_refcount

### CODE REVIEW

**Comment by apangin** [comment]
Thank you for the valuable improvement!

**Comment by ijuma** [comment]
FYI, this was changed back https://github.com/openjdk/jdk/commit/58a591039338c05890586876b7219fa5f1dbd1a4

**Comment by rraptorr** [comment]
This shouldn't require any changes. async-profiler will use the field it can find now.

**Comment by ijuma** [comment]
Thanks for confirming.

**Pull request merged**
