### PR TITLE
Built-in generator of Flame Graphs in SVG format

### PR DESCRIPTION
**Pull request by apangin**
- New output format: `-o svg`
- Automatically choose output format depending on file extension
- Removed references to `flamegraph.pl`

### CODE REVIEW

**Comment by apangin** [comment]
Thank you for review!

**Comment by rockiee281** [comment]
With -f flame.svg ,no output int flame.svg  but something like 'Stopped profiling after 30 seconds'. 

Without '-f' option, I can get the load trace normally. 

env: Centos 7.2, jdk8 with hotspot, 32G memory with G1,  build the async-profiler from master

**Comment by apangin** [comment]
@rockiee281 I guess an older version of `libasyncProfiler.so` had been already loaded into Java process before you started profiling with a new version. Can it be the case?

**Comment by rockiee281** [comment]
Hi, I build a fresh aysnc-profiler from source, and never use this tools before so I think there won't be any   libasyncProfiler.so load by java process before

**Comment by rockiee281** [comment]
Anyway , now I use the old way to generate colloapsed tarce file and make flame graph by flamegraph.pl . This is really great tool, thanks

**Comment by apangin** [comment]
@rockiee281 Hmm. `-f flame.svg` is also supposed to work. If it does not - it is a bug that I'd like to fix. If you can easily reproduce the problem, could you please add the following `echo` line to see the full jattach command issued by `profiler.sh`? Thanks.

```
diff --git a/profiler.sh b/profiler.sh
index 644a25b..d389950 100755
--- a/profiler.sh
+++ b/profiler.sh
@@ -45,6 +45,7 @@ check_if_terminated() {
 }

 jattach() {
+    echo $JATTACH $PID load "$PROFILER" true $1
     $JATTACH $PID load "$PROFILER" true $1 > /dev/null
     RET=$?
```

**Comment by rockiee281** [comment]
@apangin  this output 2 lines：
./build/jattach 134836 load /<dir_where_build>/async-profiler/build/libasyncProfiler.so true start,event=cpu,file=flame1.svg,svg
./build/jattach 134836 load /<dir_where_build>/async-profiler/build/libasyncProfiler.so true stop,file=flame1.svg,svg

And this time it works well. I think its my mistake. Thanks you  👍

**Pull request merged**
