### PR TITLE
Improved arguments description during error's construction

### PR DESCRIPTION
**Pull request by toktarev**

### CODE REVIEW

**Comment by toktarev** [comment]
@apangin is it better ?

**Comment by toktarev** [comment]
Ideally we need kind of https://github.com/facebook/rocksdb/blob/main/util/status.cc

**Comment by toktarev** [comment]
https://github.com/toktarev/async-profiler/commit/55fba19a6053ea5577eeb16dfaf45ffa702afdd8

This is just a draft.

What do you think about such refactoring ?

**Comment by toktarev** [comment]
@apangin,

Do you have any opinion about this work?

If this is hopeless again, I will close it (and will probably it will be my last PR to this repository ) :)

**Comment by apangin** [comment]
At the moment I'm busy with higher priority tasks, but I'll consider Error refactoring for the next major release.

I guess this won't compile on our release agent with gcc 4.7.2 because of `std::move`.
Such problems are actually a reason why I prefer to avoid dependencies on libstdc++ where possible. I'm even thinking of banning libstdc++ from the entire project, like, for example, HotSpot does.

**Comment by toktarev** [comment]
1) Removed std::move

2) ----Error refactoring for the next major release
Do you mean refactoring which I started working on?

So I can continue my work and once it will be appropriately finished you will merge it?

**Comment by toktarev** [comment]
I am Closing this PR for now due to unclear contribution policies.

Feel free to re-open it if you finally consider these changes as useful.

Thanks.

**Comment by toktarev** [comment]
@apangin 

This PR https://github.com/jvm-profiling-tools/async-profiler/pull/479 was submitted on 14 Oct 2021.

And what is wrong with this PR ? It is useful, good, bad ?
I expected the same with my (like: ok Alexander wrote some code, it is fine, but
I don't want to hurt him by closing PR and let's PR will wait forever).

I do not really understand contribution policy.

If you'd describe contribution policies, it would be more clear.

I understand that you are busy, but please try to understand contributors:

People do not want to write some code and then wait....., wait..., 
without understanding: if their work will be used or not.

This is psychologically difficult at least for me.

Let's check how it happened here: https://github.com/STEllAR-GROUP/hpx/pull/5288.

Guys were polite and made reviews in very short terms.

**Comment by apangin** [comment]
>This PR #479 was submitted on 14 Oct 2021.
> And what is wrong with this PR ?

Don't worry about others; the author of that PR is aware of the situation, we keep in touch.
Especially if you knew about that PR, there was no need to create a duplicate.

> I do not really understand contribution policy.

Answered above. In short, contributions are welcome, but there are no guarantees that any PR will be accepted.
You've raised a valid point though: I think I'll write some document regarding contribution.

> People do not want to write some code and then wait....., wait...,
> without understanding: if their work will be used or not.

I must confess: I don't know this myself. So the issue remains open.

Depending on how the project evolves, the proposed changes may be later merged, refactored, or rejected.
In some cases this make take years, and that's fine. async-profiler is not unique in this sense: try browsing open JDK issues, and you'll find some from the previous century! :)

However, as to these particular changes, I explicitly stated that I'll consider them for the next major release, so your complaints are not really justified.

> This is psychologically difficult at least for me.

Sorry about that. I already feel myself your personal psychologist by kindly responding to your frustration reports again and again. This will be the last session though.

**Comment by toktarev** [comment]
---so your complaints are not really justified

There are no complaints. I've opened PR don't see any reactions and closed it.
No problem.

---I already feel myself your personal psychologist

To be honest. Me too. 
You can ignore opened PR and some changes, but you can not ignore that I just closed it.
Looks like "every personal psychologist" really needs their own psychologist.

---This will be the last session though

No problem. As I said before, without a clear contribution policy - it was my last PR to this repository.

**Pull request closed without merging**
